variable "nic_name" {}
variable "resource_group_location" {}
variable "resource_group_name" {}
variable "virtual_machine_name" {}
variable "vm_size" {}
variable "username" {}
variable "admin_password" {}
variable "image_publisher" {}
variable "image_offer" {}
variable "image_sku" {}
variable "image_version" {}
variable "PIP_name" {}
variable "subnet_name" {}
variable "virtual_network_name" {}
